kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway-configmap
  namespace: default
data:
  PORT: "{{ toString .Values.service.port }}"
  ENV: prod
  AUTH_URL: http://auth:8081
  WEB_URL: {{ .Values.host }}
