apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      # imagePullSecrets:
      #   - name: registry-secret
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.deployment.container.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.deployment.container.port }}
          envFrom:
            - configMapRef:
                name: gateway-configmap
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "1024m"

          # envFrom:
          #   - configMapRef:
          #       name: gateway-configmap
          #   - secretRef:
          #       name: gateway-secret
